export default {
    authenticated: false,
    user: null,
    accounts: [],
    accountsTotal: null,
    accountsCurrentPage: 1,
    accountTypes: [],
    banks: [],
    currencies: [],
    depositTransactions:[],
    depositTransactionsTotal: null,
    depositTransactionsCurrentPage: 1,
    withdrawTransactions:[],
    withdrawTransactionsTotal: null,
    withdrawTransactionsCurrentPage: 1,
    transferTransactions:[],
    transferTransactionsTotal: null,
    transferTransactionsCurrentPage: 1,

}
